### PR TITLE
Remove `omitempty` from `DataSlice` fields.

### PR DESCRIPTION
**Pull request by omarkilani**
`offset` and `length` can both be `0` in RPC calls (c.f. https://docs.solana.com/developing/clients/jsonrpc-api#results-27)

The current code stops JSON from encoding the fields if they're `0`, thus breaking RPC calls with:

{"code":-32602,"message":"Invalid params: missing field `offset`.","data":null}

### CODE REVIEW

**Comment by yihau** [comment]
I'm thinking make them become pointers. if we remove `omitempty`, we wouldn't use them individually.

**Comment by omarkilani** [comment]
@yihau as far as I'm aware both fields should always be specified by the user in every RPC call, according to the Solana RPC docs.

C.f. 
https://github.com/solana-labs/solana/blob/f1427dd90cbde993f489232a13bd89f836ed98bd/web3.js/src/connection.ts#L2555

**Comment by yihau** [comment]
oh... yeah. you're right. I got confused by the test result. I'll remove some test cases in this PR later.

**Comment by yihau** [comment]
Thank you for the patching!

**Comment by omarkilani** [comment]
@yihau any chance you could cut a release with this fix? For quality of life purposes. :)

**Comment by yihau** [comment]
sure! https://github.com/portto/solana-go-sdk/releases/tag/v1.23.0

**Pull request merged**
