### PR TITLE
Add maxSupportedTransactionVersion to getBlock RPC

### PR DESCRIPTION
**Pull request by thiagosantana-mb**
Minimal compatibility for blocks containing v0 transactions

### CODE REVIEW

**Comment by yihau** [comment]
Thank you! Just a nitpicking, could you use the full name?

```diff
- MaxTransactionVersion
+ MaxSupportedTransactionVersion
```

**Comment by thiagosantana-mb** [comment]
> ```diff
> MaxSupportedTransactionVersion
> ```

**Comment by thiagosantana-mb** [comment]
> Thank you! Just a nitpicking, could you use the full name?
> 
> ```diff
> - MaxTransactionVersion
> + MaxSupportedTransactionVersion
> ```

Sure, done

**Comment by yihau** [comment]
I just released a new version. Feel free to open issues if you have any problems or any ideas!

**Pull request merged**
