### PR TITLE
Add KeccackSecp256k1 Instruction

### PR DESCRIPTION
**Pull request by Aphoh**
New lil module with code to generate KeccakSecp256k1 Instructions for both a single signature and multiple signatures with a test against known good rust code.

Only thing that might be a blocker is the use of `ethereum/go-ethereum` as a dependency for signing, hashing, and getting an ethereum address. If you'd like me to I can try to find alternative dependencies (was thinking I might try and use [sha3](https://pkg.go.dev/golang.org/x/crypto/sha3) and the native `crypto/ecdsa` instead).

### CODE REVIEW

**Comment by yihau** [comment]
Thank for this PR! That's very awesome.
Yup, as you say. It would be better if you can get rid of `ethereum/go-ethereum` but current is an acceptable version.
Let me know if you want to try to find an alternative or you want to remain current version.

**Comment by Aphoh** [comment]
@yihau Found a reasonable alternative in [`ipsn/go-secp256k1`](https://github.com/ipsn/go-secp256k1). The `go.sum` looks much more reasonable now. Tests should all pass. I'm happy with this if you are.

**Comment by Aphoh** [comment]
^ just a lil change, made the `Sign` method private. Better not to expose it.

**Comment by yihau** [comment]
The lib looks good. I prefer to use it! Thank you🙏

**Comment by Aphoh** [comment]
@yihau anything blocking this from being merged?

**Pull request merged**
